### ISSUE TITLE
OverflowError: timestamp out of range for platform time_t

### ISSUE THREAD

**Issue by ThinkTransit** [adafruit/Adafruit_CircuitPython_datetime#10] opened 2021-07-26 14:24 UTC
Any ideas what could be causing this overflow error?

Thanks

Hardware: featherS2

```
Adafruit CircuitPython 7.0.0-alpha.4 on 2021-07-08; FeatherS2 with ESP32S2
>>> from adafruit_datetime import time, datetime
>>> datetime.now()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lib/adafruit_datetime.py", line 1356, in now
  File "/lib/adafruit_datetime.py", line 1328, in fromtimestamp
  File "/lib/adafruit_datetime.py", line 1309, in _fromtimestamp
OverflowError: timestamp out of range for platform time_t
>>>
```

**Comment by DJDevon3** [comment] 2024-03-21 06:07
@tekktrik Time to revisit?  That was a 7.x alpha from 2021...  

```
Adafruit CircuitPython 9.0.0 on 2024-03-19; FeatherS3 with ESP32S3
>>> from adafruit_datetime import time, datetime
>>> datetime.now()
datetime.datetime(2000, 1, 1, 0, 23, 52)
```
Seems ok to me with 9.0.

Found this issue by going to https://circuitpython.org/contributing/open-issues :)

**Comment by tekktrik** [comment] 2024-03-21 13:54
Based on the version I assume this occurred in (`1.1.3`), it actually seems to be an issue with the board firmware causing the `OverflowError`.  I'd be good closing if this worked on a FeatherS2 with ESP32S2 with a current CircuitPython version.

**Comment by DJDevon3** [comment] 2024-03-21 15:20
I have both an Unexpected Maker Feather S2 & FeatherS3.  Now confirmed working on both.

```
Adafruit CircuitPython 9.0.0 on 2024-03-19; FeatherS2 with ESP32S2
>>> from adafruit_datetime import time, datetime
>>> datetime.now()
datetime.datetime(2000, 1, 1, 0, 2, 36)
>>> 
```

**Closed as completed** 2024-03-21 15:33 UTC
Labels: bug
