### ISSUE TITLE
datetime.fromtimestamp() overflows in all cases

### ISSUE THREAD

**Issue by thomaspaulin** [adafruit/Adafruit_CircuitPython_datetime#25] opened 2024-03-07 18:48 UTC
I'm running CircuitPython 8.2.9 on a Matrix Portal M4 board and I've not been able to get `datetime.fromtimestamp()` working with any parameters.

For example I ran the following in the REPL
```
>>> datetime.fromtimestamp(0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "adafruit_datetime.py", line 1370, in fromtimestamp
  File "adafruit_datetime.py", line 1349, in _fromtimestamp
OverflowError: timestamp out of range for platform time_t
```
I see the same error when using different values of int and float dtypes.

**Comment by FoamyGuy** [comment] 2024-11-13 18:44
I think this is to do with CircuitPython using 1/1/2000 as a datetime baseline, but I am not 100% certain. 

Dates on or before then raise the overflow error that you saw. This REPL code shows that 1/1/2000 raises the error and 1/2/2000 does not:
```
>>> dt = datetime(2000, 1, 2, 0, 0)
>>> dt.timestamp()
9.46771e+08
>>> dt = datetime(2000, 1, 1, 0, 0)
>>> dt.timestamp()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lib/adafruit_datetime.py", line 1524, in timestamp
  File "/lib/adafruit_datetime.py", line 1449, in _mktime
  File "/lib/adafruit_datetime.py", line 1437, in local
OverflowError: timestamp out of range for platform time_t
```
This is when accessing `.timestamp()` but I believe the same rule applies to `fromtimestamp()`...

```
>>> datetime.fromtimestamp(946771000)
datetime.datetime(2000, 1, 1, 23, 55, 44)
>>> datetime.fromtimestamp(946620000)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lib/adafruit_datetime.py", line 1370, in fromtimestamp
  File "/lib/adafruit_datetime.py", line 1349, in _fromtimestamp
OverflowError: timestamp out of range for platform time_t
```

Closing this for now because I believe it's expected behavior for CircuitPython. If there is a desire to change it feel free to re-open this, but I think it will need to involve the core dev team and perhaps would require further changes inside the core to support.

**Closed as completed by FoamyGuy** 2024-11-13 18:44 UTC
